[workspace]
resolver = "3"
members = [
    "yevm",
    "yevm-base",
    "yevm-core",
    "yevm-gate",
    "yevm-lens",
    "yevm-misc",
    "yevm-test",
    "yevm-wasm",
]

[profile.release]
debug = true

[workspace.dependencies]
eyre = "0.6"
thiserror = "2.0"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1"
ruint = "1.17"
ethnum = "1.5"
keccak-asm = "0.1"
tiny-keccak = { version = "2", features = ["keccak"] }
reqwest = { version = "0.13", features = ["json"] }
k256 = { version = "0.13", features = ["ecdsa"] }
futures = "0.3"
ahash = "0.8"
yevm-base = { version = "0.1.0", path = "./yevm-base" }
yevm-core = { version = "0.1.0", path = "./yevm-core" }
yevm-lens = { version = "0.1.0", path = "./yevm-lens" }
yevm-misc = { version = "0.1.0", path = "./yevm-misc" }
yevm-wasm = { version = "0.1.0", path = "./yevm-wasm" }
