[package]
name = "yaevmi-gate"
version = "0.1.0"
edition = "2021"

[dependencies]
yaevmi-base = { workspace = true }
yaevmi-core = { workspace = true }
yaevmi-misc = { workspace = true }
eyre = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
hex = { workspace = true }
k256 = { workspace = true }
futures = { workspace = true }
tokio = { version = "1", features = ["full"] }
rand = "0.8"
axum = "0.8"
dotenvy = "0.15"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
